services:
  - type: web
    name: trigger-mcserver
    env: python
    plan: free
    region: frankfurt
    buildCommand: ""
    startCommand: python api_server.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: USERNAME
        sync: false
      - key: PASSWORD
        sync: false